baseURL = 'https://acs229.com'
languageCode = 'en-us'
title = 'acs229.com'

theme = 'risotto'

[menus]
[[menus.main]]
  name = 'Resume'
  url = '/resume'
  weight = 200
[[menus.main]]
  name = 'Contact'
  url = '/contact'
  weight = 300